### ISSUE TITLE
Save button on Document Form does not work

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/qgis-document-management-system-plugin#21]
Hello,

When you click on the SAVE button on the document form, it does not commit the new values in the PostgreSQL db.

![image](https://user-images.githubusercontent.com/72449015/129750137-ecf57fa9-9d21-4e96-ae43-0787fd5c8231.png)

 You need to return to the parent form, and click on the SAVE button to commit the new values

![image](https://user-images.githubusercontent.com/72449015/129750188-095f74ea-03e0-43cd-b056-dbe2ba199d03.png)

**Comment by domi4484** [comment]
I don't have any save button in the attachment widget, how do you get this visible?
![image](https://user-images.githubusercontent.com/9881900/130183494-78b32b50-e989-4760-a347-5cee5e1fc74c.png)

**Comment by jpdupuy** [comment]
I work with QGIS 3.20
![image](https://user-images.githubusercontent.com/72449015/130187337-4042534f-6770-4fcf-bba5-d84a42b59991.png)
at first click on the EDIT button, the SAVE button will appear on the form
![image](https://user-images.githubusercontent.com/72449015/130187823-febefb5e-60e6-4622-ac60-644dcbeea6b4.png)
Then select the attachement button
![image](https://user-images.githubusercontent.com/72449015/130187877-6a42f8ad-8b4f-4b95-ab14-3bb851ef4db5.png)

**Comment by domi4484** [comment]
Ok now I have found it, it appears when you choose the "use hyperlink" option.
![image](https://user-images.githubusercontent.com/9881900/130197774-1133709b-a19c-4e2d-a184-416b580c8f2b.png)

This save button is only to change between an "Edit mode" and a "Display hyperlink mode" of the attachment widget. It has nothing to do with persisting data into the database.

The icons used in this context are leading to confusion because are the same used to toggle editing/saving edits of a layer.
I'll suggest opening an issue in the QGIS project pointing out the problem.

**Comment by jpdupuy** [comment]
yes you can close it
